packages:
  - apps/*
  - packages/*
  - docs

catalog:
  '@hookform/resolvers': 5.1.1
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-router': ^1.127.8
  '@tanstack/react-router-devtools': ^1.127.8
  '@tanstack/react-table': ^8.21.3
  '@tanstack/router-plugin': ^1.127.8

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.1
    '@vitejs/plugin-react': ^4.5.2
    eslint: ^9.29.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    typescript: ~5.8.3
    typescript-eslint: ^8.34.1
    vite: ^7.0.0
    zx: ^8.7.1
  styles:
    '@iconify-json/fluent': ^1.2.29
    '@iconify/react': ^6.0.0
    '@unocss/preset-icons': ^66.4.2
    '@unocss/reset': ^66.4.2
    antd: ^5.27.1
    next-themes: ^0.4.6
    unocss: ^66.4.2
    unocss-preset-scrollbar: ^3.2.0

  types:
    '@types/node': ^24.0.5
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
  utils:
    '@ant-design/v5-patch-for-react-19': ^1.0.3
    es-toolkit: ^1.39.10
    fs-extra: ^11.3.0
    globals: ^16.2.0
    i18next: ^25.2.1
    i18next-http-backend: ^3.0.2
    react-hook-form: 7.60.0
    react-i18next: ^15.5.3
    yaml: ^2.8.0
    zod: 4.0.5
  web:
    react: ^19.1.0
    react-dom: ^19.1.0

onlyBuiltDependencies:
  - simple-git-hooks
