packages:
  - apps/*
  - packages/*
  - docs

catalog:
  '@hookform/resolvers': 5.1.1
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-router': ^1.127.8
  '@tanstack/react-router-devtools': ^1.127.8
  '@tanstack/react-table': ^8.21.3
  '@tanstack/router-plugin': ^1.127.8
  next-themes: ^0.4.6

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.1
    '@vitejs/plugin-react': ^4.5.2
    eslint: ^9.29.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    typescript: ~5.8.3
    typescript-eslint: ^8.34.1
    vite: ^7.0.0
    zx: ^8.7.1
  styles:
    '@iconify/react': ^6.0.0
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-collapsible': ^1.1.11
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': 2.1.15
    '@radix-ui/react-label': 2.1.7
    '@radix-ui/react-radio-group': ^1.3.7
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slot': 1.2.3
    '@radix-ui/react-switch': ^1.2.5
    '@radix-ui/react-tooltip': ^1.2.7
    '@tailwindcss/vite': ^4.1.11
    class-variance-authority: 0.7.1
    clsx: ^2.1.1
    lucide-react: 0.525.0
    sonner: ^2.0.6
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.4
  types:
    '@types/node': ^24.0.5
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
  utils:
    fs-extra: ^11.3.0
    globals: ^16.2.0
    i18next: ^25.2.1
    i18next-http-backend: ^3.0.2
    react-hook-form: 7.60.0
    react-i18next: ^15.5.3
    yaml: ^2.8.0
    zod: 4.0.5
  web:
    react: ^19.1.0
    react-dom: ^19.1.0

onlyBuiltDependencies:
  - simple-git-hooks
