// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/api/login":{"post":{"description":"验证用户，返回 JWT Token","consumes":["application/json"],"produces":["application/json"],"tags":["auth"],"summary":"登录","parameters":[{"description":"Login credentials","name":"body","in":"body","required":true,"schema":{"$ref":"#/definitions/admingo_internal_modules_auth_dto.LoginDTO"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/admingo_internal_pkg_response.Response-admingo_internal_modules_auth_dto_LoginResponseDTO"}}}}},"/api/register":{"post":{"description":"注册新用户并自动的登录","consumes":["application/json"],"produces":["application/json"],"tags":["auth"],"summary":"注册","parameters":[{"description":"User registration data","name":"body","in":"body","required":true,"schema":{"$ref":"#/definitions/admingo_internal_modules_auth_dto.LoginDTO"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/admingo_internal_pkg_response.Response-admingo_internal_modules_auth_dto_LoginResponseDTO"}}}}}},"definitions":{"admingo_internal_modules_auth_dto.LoginDTO":{"type":"object","required":["password","username"],"properties":{"password":{"type":"string"},"username":{"type":"string"}}},"admingo_internal_modules_auth_dto.LoginResponseDTO":{"type":"object","properties":{"token":{"type":"string"}}},"admingo_internal_pkg_response.Response-admingo_internal_modules_auth_dto_LoginResponseDTO":{"type":"object","properties":{"code":{"type":"integer"},"data":{"$ref":"#/definitions/admingo_internal_modules_auth_dto.LoginResponseDTO"},"message":{"type":"string"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "AdminGO API",
	Description:      "This is the backend service for AdminGO.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
