database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: admingo
  charset: utf8mb4
  parse_time: true
  loc: Local

server:
  port: 8080

i18n:
  localsPath: "../../locals"

jwt:
  secret: qiyuor2
